apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kbe-rest-service
  name: kbe-rest-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: kbe-rest-deployment
  type: NodePort
status:
  loadBalancer: {}
