apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kbe-rest-deployment
  name: kbe-rest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbe-rest-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kbe-rest-deployment
    spec:
      containers:
      - image: springframeworkguru/kbe-rest-brewery
        name: kbe-rest-brewery
        resources: {}
        env:
          - name: LOGGING_LEVEL_GURU_SPRINGFRAMEWORK_SFGRESTBREWERY
              value: "info"
          - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
              value: "true"
          - name: MANAGEMENT_HEALTH_READINESS_ENABLED
              value: "true"
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 10
status: {}
