apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kbe-rest6-deploy
  name: kbe-rest6-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbe-rest6-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kbe-rest6-deploy
    spec:
      containers:
      - image: spring-6-kbe-rest-brewery:k8s
        name: spring-6-kbe-brewery
        env:
          - name: LOGGING_LEVEL_GURU_SPRINGFRAMEWORK_SFGRESTBREWERY
            value: "info"
          - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
            value: "true"
          - name: MANAGEMENT_HEALTH_READINESSSTATE_ENABLED
            value: "true"
          - name: MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED
            value: "true"
          - name: SERVER_SHUTDOWN
            value: "graceful"
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          # wait 3s before performing the first probe
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          # wait 3s before performing the first probe
          initialDelaySeconds: 15
        # belongs to SERVER_SHUTDOWN property
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 15" ]
        resources: {}
status: {}
